-- MySQL Script generated by MySQL Workbench
-- 07/19/16 15:24:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema jdbcdata
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jdbcdata
-- -----------------------------------------------------
--CREATE SCHEMA IF NOT EXISTS `jdbcdata` DEFAULT CHARACTER SET utf8 ;
DROP DATABASE IF EXISTS `jdbcdata`;
CREATE DATABASE `jdbcdata`
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

USE `jdbcdata` ;

-- -----------------------------------------------------
-- Table `jdbcdata`.`Statuses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jdbcdata`.`Statuses` ;

CREATE TABLE IF NOT EXISTS `jdbcdata`.`Statuses` (
  `status_id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jdbcdata`.`Documents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jdbcdata`.`Documents` ;

CREATE TABLE IF NOT EXISTS `jdbcdata`.`Documents` (
  `document_id` INT NOT NULL AUTO_INCREMENT,
  `data_create` DATE,
  `doc_type` VARCHAR(45),
  `status_id` INT,
  PRIMARY KEY (`document_id`),
  INDEX `Index_status_id` (`status_id` ASC),
  CONSTRAINT `FK_Documents_Statuses`
    FOREIGN KEY (`status_id`)
    REFERENCES `jdbcdata`.`Statuses` (`status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jdbcdata`.`Mails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jdbcdata`.`Mails` ;

CREATE TABLE IF NOT EXISTS `jdbcdata`.`Mails` (
  `document_id` INT NOT NULL,
  `header` VARCHAR(256),
  `body` TEXT,
  `attachment` BLOB,
  PRIMARY KEY (`document_id`),
  CONSTRAINT `fk_Mails_Documents`
    FOREIGN KEY (`document_id`)
    REFERENCES `jdbcdata`.`Documents` (`document_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jdbcdata`.`Status_hystory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `jdbcdata`.`Status_hystory` ;

CREATE TABLE IF NOT EXISTS `jdbcdata`.`Status_hystory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_change` DATETIME,
  `document_id` INT NULL,
  `status_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `document_id` (`document_id` ASC),
  INDEX `status_id` (`status_id` ASC),
  CONSTRAINT `FK_StatusHystory_Documents`
    FOREIGN KEY (`document_id`)
    REFERENCES `jdbcdata`.`Documents` (`document_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_StatusHystory_Statuses`
    FOREIGN KEY (`status_id`)
    REFERENCES `jdbcdata`.`Statuses` (`status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


INSERT INTO `jdbcdata`.`statuses` (Name) VALUES ("Создан"), ("Обрабатывается в банке"), ("Принят"), ("Отбакован");

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
